version: '3'

services:
  frontend:
    build: .
    ports:
      - "80:3000"
    environment:
      - API_URL=http://api:8080
    depends_on:
      - api
  api:
    image: your-api-image:latest
    ports:
      - "8080:8080"