version: '3'

services:
  frontend:
    build: 
       dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      - API_URL=http://api:8080
    depends_on:
      - api
    image: api-image:latest
  ngnix-server:
  image: ngnix
  container_name: ngnix-server-demo
  ports:
      - 8080:80
